
#include "../../../Synth_system/Common.h"

#define VIDEO_CTRL_ADDR (XPAR_VIDEOCONTROLLER_0_BASEADDR)
#define VIDEO_FRAME_BUFFERS_ADDR (0x10000000)
#define VIDEO_FRAME_BUFFER_ADDR(fb) (VIDEO_FRAME_BUFFERS_ADDR+0x00700000*(fb))
#define VIDEO_FRAME_BUFFER_SIZE (1920*1080*2)

#define VIDEO_CTRL_ACTIVATE_OFF (4*0)
#define VIDEO_CTRL_ACTIVATE_REG REG32(VIDEO_CTRL_ADDR+VIDEO_CTRL_ACTIVATE_OFF)

#define VIDEO_CTRL_FB1ADDR_OFF (4*1)
#define VIDEO_CTRL_FB1ADDR_REG REG32(VIDEO_CTRL_ADDR+VIDEO_CTRL_FB1ADDR_OFF)

#define VIDEO_CTRL_FB2ADDR_OFF (4*2)
#define VIDEO_CTRL_FB2ADDR_REG REG32(VIDEO_CTRL_ADDR+VIDEO_CTRL_FB2ADDR_OFF)

#define VIDEO_CTRL_FBSIZE_OFF (4*3)
#define VIDEO_CTRL_FBSIZE_REG REG32(VIDEO_CTRL_ADDR+VIDEO_CTRL_FBSIZE_OFF)

#define VIDEO_CTRL_FBSELECT_OFF (4*4)
#define VIDEO_CTRL_FBSELECT_REG REG32(VIDEO_CTRL_ADDR+VIDEO_CTRL_FBSELECT_OFF)


int InitVideoController();

