
#include "../../../Synth_system/Common.h"

#define VIDEO_DMA_ADDR 0x41000000


#define VDMA_MM2S_CTRL_OFF 0x00
#define VDMA_MM2S_CTRL_REG Reg32(VIDEO_DMA_ADDR+VDMA_MM2S_CTRL_OFF)
typedef struct
{
    union
    {
        u32 DWord;
        struct
        {
            u8 IRQDelayCount;
            u8 IRQFrameCount;
            u8 RepeatEn:1;
            u8 ErrIrqEn:1;
            u8 DelayCountIrqEn:1;
            u8 FrameCountIrqEn:1;
            u8 ReadFbPtr:4;
            u8 GenLockSrc:1;
            u8 RESERVED_1:2;
            u8 FrameCountEn:1;
            u8 GenLockEn:1;
            u8 Reset:1;
            u8 CircularPark:1;
            u8 Run:1;
        } Bitwise;
    } MM2S_Ctl;
} MM2S_Ctl;
#define VDMA_MM2S_CTRL_ST *((MM2S_Ctl *)MEM32(VIDEO_DMA_ADDR+VDMA_MM2S_CTRL_OFF))


#define VDMA_MM2S_STATUS_OFF 0x04
#define VDMA_MM2S_STATUS_REG Reg32(VIDEO_DMA_ADDR+VDMA_MM2S_STATUS_OFF)

#define VDMA_REG_IDX_OFF 0x14
#define VDMA_REG_IDX_REG Reg32(VIDEO_DMA_ADDR+VDMA_REG_IDX_OFF)

#define VDMA_PARK_PTR_OFF 0x28
#define VDMA_PARK_PTR_REG Reg32(VIDEO_DMA_ADDR+VDMA_PARK_PTR_OFF)

#define VDMA_VERSION_OFF 0x2C
#define VDMA_VERSION_REG Reg32(VIDEO_DMA_ADDR+VDMA_VERSION_OFF)

#define VDMA_S2MM_CTRL_OFF 0x30
#define VDMA_S2MM_CTRL_REG Reg32(VIDEO_DMA_ADDR+VDMA_S2MM_CTRL_OFF)

#define VDMA_S2MM_STATUS_OFF 0x34
#define VDMA_S2MM_STATUS_REG Reg32(VIDEO_DMA_ADDR+VDMA_S2MM_STATUS_OFF)

#define VDMA_S2MM_ERR_INT_MASK_OFF 0x3C
#define VDMA_S2MM_ERR_INT_MASK_REG Reg32(VIDEO_DMA_ADDR+VDMA_S2MM_ERR_INT_MASK_OFF)

#define VDMA_S2MM_REG_IDX_OFF 0x44
#define VDMA_S2MM_REG_IDX_REG Reg32(VIDEO_DMA_ADDR+VDMA_S2MM_REG_IDX_OFF)

#define VDMA_MM2S_VSIZE_OFF 0x50
#define VDMA_MM2S_VSIZE_REG Reg32(VIDEO_DMA_ADDR+VDMA_MM2S_VSIZE_OFF)

#define VDMA_MM2S_HSIZE_OFF 0x54
#define VDMA_MM2S_HSIZE_REG Reg32(VIDEO_DMA_ADDR+VDMA_MM2S_HSIZE_OFF)

#define VDMA_MM2S_FRAME_DELAY_STRIDE_OFF 0x58
#define VDMA_MM2S_FRAME_DELAY_STRIDE_REG Reg32(VIDEO_DMA_ADDR+VDMA_MM2S_FRAME_DELAY_STRIDE_OFF)

#define VDMA_MM2S_START_ADDR_OFF(fb) (0x5C+((fb)-1)*4)
#define VDMA_MM2S_START_ADDR_REG(fb) Reg32(VIDEO_DMA_ADDR+VDMA_MM2S_START_ADDR_OFF(fb))

#define VDMA_S2MM_VSIZE_OFF 0xA0
#define VDMA_S2MM_VSIZE_REG Reg32(VIDEO_DMA_ADDR+VDMA_S2MM_VSIZE_OFF)

#define VDMA_S2MM_HSIZE_OFF 0xA4
#define VDMA_S2MM_HSIZE_REG Reg32(VIDEO_DMA_ADDR+VDMA_S2MM_HSIZE_OFF)

#define VDMA_S2MM_FRAME_DELAY_STRIDE_OFF 0xA8
#define VDMA_S2MM_FRAME_DELAY_STRIDE_REG Reg32(VIDEO_DMA_ADDR+VDMA_S2MM_FRAME_DELAY_STRIDE_OFF)

#define VDMA_S2MM_START_ADDR_OFF(fb) (0xAC+((fb)-1)*4)
#define VDMA_S2MM_START_ADDR_REG(fb) Reg32(VIDEO_DMA_ADDR+VDMA_S2MM_START_ADDR_OFF(fb))

#define VDMA_ENABLE_VERITCAL_FLIP_OFF 0xEC
#define VDMA_ENABLE_VERITCAL_FLIP_REG Reg32(VIDEO_DMA_ADDR+VDMA_ENABLE_VERITCAL_FLIP_OFF)



int InitVideoDMA();





