
#include "../../../Synth_system/Common.h"

#define VIDEO_CTRL_ADDR (XPAR_VIDEOCONTROLLER_0_BASEADDR)
#define VIDEO_FRAME_BUFFERS_ADDR (0x10000000)
#define VIDEO_FRAME_BUFFER_ADDR(fb) (VIDEO_FRAME_BUFFERS_ADDR+0x00700000*(fb))
#define VIDEO_FRAME_BUFFER_SIZE (1920*1080*2)

#define VIDEO_CTRL_ACTIVATE_OFF 0x00
#define VIDEO_CTRL_ACTIVATE_REG Reg32(VIDEO_CTRL_ADDR+VIDEO_CTRL_ACTIVATE_OFF)

#define VIDEO_CTRL_FB1ADDR_OFF 0x04
#define VIDEO_CTRL_FB1ADDR_REG Reg32(VIDEO_CTRL_ADDR+VIDEO_CTRL_FB1ADDR_OFF)

#define VIDEO_CTRL_FB2ADDR_OFF 0x08
#define VIDEO_CTRL_FB2ADDR_REG Reg32(VIDEO_CTRL_ADDR+VIDEO_CTRL_FB2ADDR_OFF)

#define VIDEO_CTRL_FBSIZE_OFF 0x10
#define VIDEO_CTRL_FBSIZE_REG Reg32(VIDEO_CTRL_ADDR+VIDEO_CTRL_FBSIZE_OFF)


#define VIDEO_CTRL_FBSELECT_OFF 0x14
#define VIDEO_CTRL_FBSELECT_REG Reg32(VIDEO_CTRL_ADDR+VIDEO_CTRL_FBSELECT_OFF)

int InitVideoController();

