

#define SYNTH_ADDR (XPAR_APBSLAVE_BREAKOUT_SYNTH_BASEADDR)
#define SYNTH_ACCESS_RAW() (*(uint32_t *)(SYNTH_ADDR))
#define SYNTH_ACCESS(reg) (*(uint32_t *)(SYNTH_ADDR + 4*(reg)))

#define CHANNEL_OFFSET (0x00000000)

