

#define SYNTH_ADDR (XPAR_SYNTH_BASEADDR)

#define SYNTH_CHANNEL_OFF(ch) (0x1000*(ch))

#define SYNTH_INCR_OFF 0x00
#define SYNTH_INCR_REG(ch) REG32(SYNTH_ADDR+SYNTH_CHANNEL_OFF(ch)+SYNTH_INCR_OFF)

#define SYNTH_WAVETYPE_OFF 0x04
#define SYNTH_WAVETYPE_REG(ch) REG32(SYNTH_ADDR+SYNTH_CHANNEL_OFF(ch)+SYNTH_WAVETYPE_OFF)

#define SYNTH_ATTACK_OFF 0x08
#define SYNTH_ATTACK_REG(ch) REG32(SYNTH_ADDR+SYNTH_CHANNEL_OFF(ch)+SYNTH_ATTACK_OFF)

#define SYNTH_DECAY_OFF 0x0C
#define SYNTH_DECAY_REG(ch) REG32(SYNTH_ADDR+SYNTH_CHANNEL_OFF(ch)+SYNTH_DECAY_OFF)

#define SYNTH_SUSTAIN_OFF 0x10
#define SYNTH_SUSTAIN_REG(ch) REG32(SYNTH_ADDR+SYNTH_CHANNEL_OFF(ch)+SYNTH_SUSTAIN_OFF)

#define SYNTH_RELEASE_OFF 0x14
#define SYNTH_RELEASE_REG(ch) REG32(SYNTH_ADDR+SYNTH_CHANNEL_OFF(ch)+SYNTH_RELEASE_OFF)

#define SYNTH_GATE_OFF 0x18
#define SYNTH_GATE_REG(ch) REG32(SYNTH_ADDR+SYNTH_CHANNEL_OFF(ch)+SYNTH_GATE_OFF)

#define SYNTH_ENVELOPE_OFF 0x1C
#define SYNTH_ENVELOPE_REG(ch) REG32(SYNTH_ADDR+SYNTH_CHANNEL_OFF(ch)+SYNTH_ENVELOPE_OFF)

#define SYNTH_ADSR_STATE_OFF 0x20
#define SYNTH_ADSR_STATE_REG(ch) REG32(SYNTH_ADDR+SYNTH_CHANNEL_OFF(ch)+SYNTH_ADSR_STATE_OFF)

#define SYNTH_RUNNING_OFF 0x24
#define SYNTH_RUNNING_REG(ch) REG32(SYNTH_ADDR+SYNTH_CHANNEL_OFF(ch)+SYNTH_RUNNING_OFF)


#define KEYBOARD_DRIVE_OFF 0x00
#define KEYBOARD_DRIVE_ADDR (XPAR_APBSLAVE_BREAKOUT_KEYBOARD_BASEADDR + KEYBOARD_DRIVE_OFF)
#define KEYBOARD_DRIVE_REG REG32(KEYBOARD_DRIVE_ADDR)

#define KEYBOARD_SENSE_OFF 0x04
#define KEYBOARD_SENSE_ADDR (XPAR_APBSLAVE_BREAKOUT_KEYBOARD_BASEADDR + KEYBOARD_SENSE_OFF)
#define KEYBOARD_SENSE_REG REG32(KEYBOARD_SENSE_ADDR)

#define MAX_CHANNELS 16

/*
0: Unpressed
1: KeyDown
2: KeyPressed
3: KeyUp
*/
extern u8 KeyState[61];
extern u8 KeyChannel[sizeof(KeyState)];
extern u8 KeyOctaveOffset;

extern u32 NoteIncrs[96];

